# Generated by Django 5.2.14 on 2026-06-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitrecord",
            name="event",
        ),
        migrations.RemoveField(
            model_name="visitrecord",
            name="user",
        ),
        migrations.RemoveField(
            model_name="visitrecordphoto",
            name="visit_record",
        ),
        migrations.DeleteModel(
            name="UserEventStatus",
        ),
        migrations.DeleteModel(
            name="VisitRecord",
        ),
        migrations.DeleteModel(
            name="VisitRecordPhoto",
        ),
    ]
