# Generated by Django 5.2.14 on 2026-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_visitrecord_event_remove_visitrecord_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="poster_image",
            field=models.ImageField(blank=True, null=True, upload_to="event-posters/"),
        ),
    ]
