# Generated by Django 5.2.14 on 2026-06-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_add_event_poster_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="view_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
