# Generated by Django 5.2.14 on 2026-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_add_event_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
