# Generated by Django 5.2.14 on 2026-08-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_add_event_verified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="poster_image",
        ),
    ]
