# Generated by Django 5.2.14 on 2026-06-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("featured_categories", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Home page configuration",
            },
        ),
    ]
