# Generated by Django 5.2.14 on 2026-07-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_create_shared_cache_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("event_list_viewed", "Event list viewed"),
                            ("event_searched", "Event searched"),
                            ("event_detail_viewed", "Event detail viewed"),
                            ("event_interested", "Event interested"),
                            ("event_planned", "Event planned"),
                            ("event_marked_visited", "Event marked visited"),
                            ("visit_record_created", "Visit record created"),
                            ("visit_photo_added", "Visit photo added"),
                        ],
                        max_length=32,
                    ),
                ),
                ("user_key", models.CharField(blank=True, max_length=64)),
                ("target_type", models.CharField(blank=True, max_length=32)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("context", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_name", "created_at"],
                        name="core_analyt_event_n_50d725_idx",
                    )
                ],
            },
        ),
    ]
