# Generated by Django 5.2.14 on 2026-07-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_analyticsevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_name",
            field=models.CharField(
                choices=[
                    ("event_list_viewed", "Event list viewed"),
                    ("event_searched", "Event searched"),
                    ("event_detail_viewed", "Event detail viewed"),
                    ("event_interested", "Event interested"),
                    ("event_planned", "Event planned"),
                    ("event_marked_visited", "Event marked visited"),
                    ("visit_record_created", "Visit record created"),
                    ("visit_photo_added", "Visit photo added"),
                    ("collection_item_created", "Collection item created"),
                    ("collection_item_updated", "Collection item updated"),
                    (
                        "collection_item_linked_to_visit",
                        "Collection item linked to visit",
                    ),
                    ("collection_item_marked_wanted", "Collection item marked wanted"),
                    (
                        "collection_item_marked_tradeable",
                        "Collection item marked tradeable",
                    ),
                ],
                max_length=32,
            ),
        ),
    ]
