# Generated by Django 5.2.17 on 2026-09-12 23:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_analyticsevent_event_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[core.validators.validate_category_slug],
                    ),
                ),
                ("label", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "palette_slot",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, unique=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
