# Generated by Django 5.2.14 on 2026-09-18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_seed_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("error_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("message_sample", models.CharField(blank=True, max_length=500)),
                (
                    "first_seen",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("count", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
