# Generated by Django 5.2.14 on 2026-07-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("home_categories", "Home categories"),
                ],
                max_length=16,
            ),
        ),
    ]
