# Generated by Django 5.2.14 on 2026-07-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_add_event_created_at"),
        ("staff", "0002_alter_staffactionlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffactionlog",
            name="target_event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="staffactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("home_categories", "Home categories"),
                    ("event_update", "Event update"),
                ],
                max_length=16,
            ),
        ),
    ]
