# Generated by Django 5.2.14 on 2026-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_staffactionlog_target_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("home_categories", "Home categories"),
                    ("event_update", "Event update"),
                    ("event_create", "Event create"),
                    ("event_unpublish", "Event unpublish"),
                    ("event_republish", "Event republish"),
                    ("event_delete", "Event delete"),
                ],
                max_length=16,
            ),
        ),
    ]
