# Generated by Django 5.2.14 on 2026-08-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_alter_staffactionlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("home_categories", "Home categories"),
                    ("event_update", "Event update"),
                    ("event_create", "Event create"),
                    ("event_unpublish", "Event unpublish"),
                    ("event_republish", "Event republish"),
                    ("event_delete", "Event delete"),
                    ("event_verify", "Event verify"),
                    ("draft_discover", "Draft discover"),
                    ("source_discover", "Source discover"),
                ],
                max_length=16,
            ),
        ),
    ]
