# Generated by Django 5.2.17 on 2026-09-06 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_alter_staffactionlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staffactionlog",
            name="target_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="staffactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("home_categories", "Home categories"),
                    ("event_update", "Event update"),
                    ("event_create", "Event create"),
                    ("event_unpublish", "Event unpublish"),
                    ("event_republish", "Event republish"),
                    ("event_delete", "Event delete"),
                    ("event_verify", "Event verify"),
                    ("draft_discover", "Draft discover"),
                    ("source_discover", "Source discover"),
                    ("staff_grant", "Staff grant"),
                    ("staff_revoke", "Staff revoke"),
                    ("user_deactivate", "User deactivate"),
                    ("user_reactivate", "User reactivate"),
                ],
                max_length=16,
            ),
        ),
    ]
