# Generated by Django 5.2.17 on 2026-09-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_staffactionlog_target_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("home_categories", "Home categories"),
                    ("event_update", "Event update"),
                    ("event_create", "Event create"),
                    ("event_unpublish", "Event unpublish"),
                    ("event_republish", "Event republish"),
                    ("event_delete", "Event delete"),
                    ("event_verify", "Event verify"),
                    ("draft_discover", "Draft discover"),
                    ("source_discover", "Source discover"),
                    ("staff_grant", "Staff grant"),
                    ("staff_revoke", "Staff revoke"),
                    ("user_deactivate", "User deactivate"),
                    ("user_reactivate", "User reactivate"),
                    ("draft_create", "Draft create"),
                    ("draft_update", "Draft update"),
                ],
                max_length=16,
            ),
        ),
    ]
