# Generated by Django 5.2.17 on 2026-09-13 04:32
#
# staff.StaffActionLog가 core.Category를 FK로 참조한다. 그래서 이 마이그레이션은
# dependencies에 core.0006_seed_categories를 선언했고, Django는 마이그레이션
# 그래프의 이 의존 관계를 보고 롤백 시 staff.0011을 core.0006보다 먼저 자동으로
# 되돌린다 — 운영자가 롤백 순서를 직접 신경 쓸 필요는 없다.
# [실측 2026-09-13, 로컬 Postgres] 두 마이그레이션이 적용된 상태에서
# `migrate core 0005`를 실행하면 "Unapplying staff.0011..." 다음
# "Unapplying core.0006..." 순으로 자동 해결되며, FK 오류 없이 성공했다(2회 재현).
# on_delete=SET_NULL은 삭제 시점의 Django ORM 동작일 뿐 DB 레벨 제약이 아니다.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_seed_categories"),
        ("staff", "0010_alter_staffactionlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffactionlog",
            name="target_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="staffactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("home_categories", "Home categories"),
                    ("event_update", "Event update"),
                    ("event_create", "Event create"),
                    ("event_unpublish", "Event unpublish"),
                    ("event_republish", "Event republish"),
                    ("event_delete", "Event delete"),
                    ("event_verify", "Event verify"),
                    ("draft_discover", "Draft discover"),
                    ("source_discover", "Source discover"),
                    ("staff_grant", "Staff grant"),
                    ("staff_revoke", "Staff revoke"),
                    ("user_deactivate", "User deactivate"),
                    ("user_reactivate", "User reactivate"),
                    ("draft_create", "Draft create"),
                    ("draft_update", "Draft update"),
                    ("draft_reopen", "Draft reopen"),
                    ("category_create", "Category create"),
                    ("category_update", "Category update"),
                    ("category_disable", "Category disable"),
                ],
                max_length=16,
            ),
        ),
    ]
