# Generated by Django 5.2.14 on 2026-07-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_agreed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
