# Generated by Django 5.2.14 on 2026-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_alter_usereventstatus_status_eventinterest"),
    ]

    operations = [
        migrations.AddField(
            model_name="usereventstatus",
            name="missed_overridden",
            field=models.BooleanField(default=False),
        ),
    ]
