# Generated by Django 5.2.14 on 2026-06-27 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0005_personalentry"),
        ("events", "0005_add_event_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visitrecord",
            name="personal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_records",
                to="archive.personalentry",
            ),
        ),
        migrations.AlterField(
            model_name="visitrecord",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_visit_records",
                to="events.event",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event__isnull", False), ("personal_entry__isnull", True)
                    ),
                    models.Q(
                        ("event__isnull", True), ("personal_entry__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="visitrecord_exactly_one_subject",
            ),
        ),
    ]
