# Generated by Django 5.2.14 on 2026-06-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0006_visitrecord_personal_entry_alter_visitrecord_event_and_more"),
        ("events", "0005_add_event_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventinterest",
            name="unique_archive_user_event_interest",
        ),
        migrations.RemoveConstraint(
            model_name="usereventstatus",
            name="unique_archive_user_event_status",
        ),
        migrations.AddField(
            model_name="eventinterest",
            name="personal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_user_interests",
                to="archive.personalentry",
            ),
        ),
        migrations.AddField(
            model_name="usereventstatus",
            name="personal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_user_statuses",
                to="archive.personalentry",
            ),
        ),
        migrations.AlterField(
            model_name="eventinterest",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_user_interests",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="usereventstatus",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_user_statuses",
                to="events.event",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventinterest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event__isnull", False), ("personal_entry__isnull", True)
                    ),
                    models.Q(
                        ("event__isnull", True), ("personal_entry__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="eventinterest_exactly_one_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventinterest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False)),
                fields=("user", "event"),
                name="unique_archive_user_event_interest",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventinterest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("personal_entry__isnull", False)),
                fields=("user", "personal_entry"),
                name="unique_archive_user_personal_interest",
            ),
        ),
        migrations.AddConstraint(
            model_name="usereventstatus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event__isnull", False), ("personal_entry__isnull", True)
                    ),
                    models.Q(
                        ("event__isnull", True), ("personal_entry__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="usereventstatus_exactly_one_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="usereventstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False)),
                fields=("user", "event"),
                name="unique_archive_user_event_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="usereventstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("personal_entry__isnull", False)),
                fields=("user", "personal_entry"),
                name="unique_archive_user_personal_status",
            ),
        ),
    ]
