# Generated by Django 5.2.14 on 2026-06-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "archive",
            "0007_remove_eventinterest_unique_archive_user_event_interest_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="personalentry",
            name="promotion_status",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("submitted", "Submitted")],
                default="",
                max_length=20,
            ),
        ),
    ]
