# Generated by Django 5.2.14 on 2026-07-10 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0008_personalentry_promotion_status"),
        ("events", "0005_add_event_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitrecord",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_user_visit_records",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="visitrecord",
            name="personal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_user_visit_records",
                to="archive.personalentry",
            ),
        ),
    ]
