# Generated by Django 5.2.14 on 2026-07-15 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0009_alter_visitrecord_event_and_more"),
        ("events", "0005_add_event_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("work_title", models.CharField(blank=True, max_length=255)),
                ("character_name", models.CharField(blank=True, max_length=255)),
                ("item_type", models.CharField(blank=True, max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                ("acquired_on", models.DateField(blank=True, null=True)),
                ("acquisition_source", models.CharField(blank=True, max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="collection-items/"
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                ("is_wanted", models.BooleanField(default=False)),
                ("tradeable_quantity", models.IntegerField(default=0)),
                ("visibility", models.CharField(default="private", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_collection_items",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_collection_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_collection_items",
                        to="archive.visitrecord",
                    ),
                ),
            ],
        ),
    ]
