# Generated by Django 5.2.14 on 2026-07-15 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0011_collectionitem_collectionitem_quantity_gte_0"),
        ("events", "0005_add_event_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("tradeable_quantity__lte", models.F("quantity"))),
                name="collectionitem_tradeable_lte_quantity",
            ),
        ),
    ]
