# Generated by Django 5.2.14 on 2026-07-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0014_alter_collectionitem_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="visit_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archive_collection_items",
                to="archive.visitrecord",
            ),
        ),
    ]
