# Generated by Django 5.2.14 on 2026-07-15 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0018_remove_goods_personal_entries"),
        ("events", "0005_add_event_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(
                fields=["user", "work_title"], name="collectionitem_user_work_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(
                fields=["user", "character_name"], name="collectionitem_user_char_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(
                fields=["user", "item_type"], name="collectionitem_user_type_idx"
            ),
        ),
    ]
