# Generated by Django 5.2.14 on 2026-07-18 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0019_collectionitem_collectionitem_user_work_idx_and_more"),
        ("events", "0005_add_event_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="client_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_token__isnull", False)),
                fields=("user", "client_token"),
                name="unique_archive_collection_item_user_client_token",
            ),
        ),
    ]
