# Generated by Django 5.2.14 on 2026-07-19 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0021_visitrecord_client_token_and_more"),
        ("events", "0005_add_event_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("interest_added", "Interest added"),
                            ("interest_removed", "Interest removed"),
                            ("status_changed", "Status changed"),
                            ("status_removed", "Status removed"),
                            ("visit_record_created", "Visit record created"),
                            ("collection_item_created", "Collection item created"),
                            ("collection_item_organized", "Collection item organized"),
                        ],
                        max_length=30,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("subject_label", models.CharField(max_length=255)),
                ("change_summary", models.JSONField(blank=True, default=dict)),
                ("operation_key", models.UUIDField(blank=True, null=True)),
                (
                    "collection_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_log_entries",
                        to="archive.collectionitem",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_activity_log_entries",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_activity_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_log_entries",
                        to="archive.visitrecord",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_at"],
                        name="archive_actlog_user_occ_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("operation_key__isnull", False)),
                        fields=("user", "kind", "operation_key"),
                        name="unique_archive_activity_log_entry_user_kind_operation_key",
                    )
                ],
            },
        ),
    ]
