# Generated by Django 5.2.14 on 2026-07-28 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0022_activitylogentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="personalentry",
            name="client_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="personalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_token__isnull", False)),
                fields=("user", "client_token"),
                name="unique_archive_personal_entry_user_client_token",
            ),
        ),
    ]
