# Generated by Django 5.2.14 on 2026-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0023_personalentry_client_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitrecordphoto",
            name="client_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="visitrecordphoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_token__isnull", False)),
                fields=("visit_record", "client_token"),
                name="unique_archive_visit_record_photo_visit_record_client_token",
            ),
        ),
    ]
