# Generated by Django 5.2.17 on 2026-08-25 09:54

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0024_visitrecordphoto_client_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=archive.models.collection_item_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="personalentry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=archive.models.personal_entry_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="visitrecordphoto",
            name="image",
            field=models.ImageField(
                upload_to=archive.models.visit_record_photo_image_upload_to
            ),
        ),
    ]
