# Generated by Django 5.2.14 on 2026-05-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(unique=True)),
                ("source_name", models.CharField(blank=True, max_length=100)),
                ("raw_title", models.CharField(blank=True, max_length=255)),
                ("raw_text", models.TextField(blank=True)),
                ("extracted_title", models.CharField(blank=True, max_length=255)),
                ("extracted_category", models.CharField(blank=True, max_length=100)),
                ("extracted_work_title", models.CharField(blank=True, max_length=255)),
                (
                    "extracted_location_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("extracted_region", models.CharField(blank=True, max_length=100)),
                ("extracted_start_date", models.DateField(blank=True, null=True)),
                ("extracted_end_date", models.DateField(blank=True, null=True)),
                ("extracted_summary", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
