# Generated by Django 5.2.14 on 2026-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0002_eventdraft_approved_at_eventdraft_rejected_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdraft",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventdraft",
            name="extraction_method",
            field=models.CharField(
                choices=[("heuristic", "Heuristic"), ("llm", "LLM")],
                default="heuristic",
                max_length=20,
            ),
        ),
    ]
