# Generated by Django 5.2.14 on 2026-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0003_eventdraft_confidence_eventdraft_extraction_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS"),
                            ("sitemap", "Sitemap"),
                            ("html", "HTML"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("link_selector", models.CharField(blank=True, max_length=255)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
        ),
    ]
