# Generated by Django 5.2.14 on 2026-08-20 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0004_draftsource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryRunnerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_heartbeat_at", models.DateTimeField()),
                ("provider", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SourceDiscoveryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("succeeded", "Succeeded"),
                            ("partially_failed", "Partially failed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("lease_token", models.CharField(blank=True, max_length=64)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("lease_count", models.PositiveSmallIntegerField(default=0)),
                ("error_summary", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS"),
                            ("sitemap", "Sitemap"),
                            ("html", "HTML"),
                        ],
                        max_length=20,
                    ),
                ),
                ("link_selector", models.CharField(blank=True, max_length=255)),
                ("sample_url", models.URLField()),
                ("official_basis", models.CharField(blank=True, max_length=500)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("promoted", "Promoted"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                (
                    "failure_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("schema", "Schema"),
                            ("duplicate", "Duplicate"),
                            ("url_safety", "URL safety"),
                            ("robots", "Robots"),
                            ("fetch", "Fetch"),
                            ("listing_extraction", "Listing extraction"),
                            ("sample_canary", "Sample canary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promoted_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="drafts.draftsource",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="drafts.sourcediscoveryrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "url"), name="uniq_source_candidate_run_url"
                    )
                ],
            },
        ),
    ]
