# Generated by Django 5.2.17 on 2026-09-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0006_alter_sourcecandidate_failure_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdraft",
            name="reopened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
