# Generated by Django 5.2.17 on 2026-09-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0007_eventdraft_reopened_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdraft",
            name="origin",
            field=models.CharField(
                choices=[("collected", "Collected"), ("user_report", "User report")],
                default="collected",
                max_length=20,
            ),
        ),
    ]
