# Generated by Django 5.2.17 on 2026-09-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0008_eventdraft_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("rss", "RSS"),
                    ("sitemap", "Sitemap"),
                    ("html", "HTML"),
                    ("instagram", "Instagram"),
                    ("x", "X"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourcecandidate",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("rss", "RSS"),
                    ("sitemap", "Sitemap"),
                    ("html", "HTML"),
                    ("instagram", "Instagram"),
                    ("x", "X"),
                ],
                max_length=20,
            ),
        ),
    ]
