# Generated by Django 5.2.17 on 2026-09-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0008_eventdraft_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdraft",
            name="discovery_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="drafts.sourcediscoveryrun",
            ),
        ),
        migrations.AddField(
            model_name="eventdraft",
            name="intake_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sourcediscoveryrun",
            name="events_attempted",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sourcediscoveryrun",
            name="events_failed",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sourcediscoveryrun",
            name="query",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="draftsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("rss", "RSS"),
                    ("sitemap", "Sitemap"),
                    ("html", "HTML"),
                    ("instagram", "Instagram"),
                    ("x", "X"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourcecandidate",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("rss", "RSS"),
                    ("sitemap", "Sitemap"),
                    ("html", "HTML"),
                    ("instagram", "Instagram"),
                    ("x", "X"),
                ],
                max_length=20,
            ),
        ),
    ]
