# Generated by Django 5.2.17 on 2026-09-11 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0009_alter_draftsource_source_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdraft",
            name="discovery_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="drafts.sourcediscoveryrun",
            ),
        ),
        migrations.AddField(
            model_name="eventdraft",
            name="intake_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
