# Generated by Django 5.2.17 on 2026-09-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0009_eventdraft_discovery_run_eventdraft_intake_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcediscoveryrun",
            name="events_excluded",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
