# Generated by Django 5.2.17 on 2026-09-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0010_eventdraft_discovery_run_eventdraft_intake_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcediscoveryrun",
            name="query",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
