# Generated by Django 5.2.17 on 2026-09-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0010_sourcediscoveryrun_events_excluded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcecandidate",
            name="failure_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("schema", "Schema"),
                    ("duplicate", "Duplicate"),
                    ("url_safety", "URL safety"),
                    ("robots", "Robots"),
                    ("fetch", "Fetch"),
                    ("listing_extraction", "Listing extraction"),
                    ("sample_canary", "Sample canary"),
                    ("sample_mismatch", "Sample mismatch"),
                    ("not_domestic", "Not domestic"),
                ],
                max_length=20,
            ),
        ),
    ]
