# Generated by Django 5.2.17 on 2026-09-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0011_sourcediscoveryrun_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcediscoveryrun",
            name="events_attempted",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sourcediscoveryrun",
            name="events_failed",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
