# Generated by Django 5.2.17 on 2026-09-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0011_alter_sourcecandidate_failure_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcediscoveryrun",
            name="event_outcomes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
