# Generated by Django 5.2.17 on 2026-09-20 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0013_alter_sourcecandidate_failure_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveryrunnerstatus",
            name="current_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="drafts.sourcediscoveryrun",
            ),
        ),
        migrations.AddField(
            model_name="discoveryrunnerstatus",
            name="offline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discoveryrunnerstatus",
            name="phase",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("exploring", "Exploring"),
                    ("reading", "Reading"),
                    ("submitting", "Submitting"),
                    ("completing", "Completing"),
                ],
                default="idle",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="discoveryrunnerstatus",
            name="phase_detail",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="discoveryrunnerstatus",
            name="phase_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
